@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"
echo ============================================================
echo  Aetheris laptop scanner - deploy V45.4 (coverage guard)
echo ============================================================
echo.
echo [0] Sanity: is THIS folder the V45.4 package?
findstr /C:"AGENT_BUILD = \"1.5.1-v45.4\"" scanner-agent\agent\__init__.py >nul || (
  echo   FAIL: scanner-agent\agent\__init__.py has no V45.4 build stamp.
  echo         You are running this from an old folder. Unzip laptop-scanner_v45_full.zip over this folder first.
  pause & exit /b 2
)
findstr /C:"SCANNER_PLUGINS_TIMEOUT_SEC=36000" .env >nul || (
  echo   FAIL: .env is not the V45 .env ^(SCANNER_PLUGINS_TIMEOUT_SEC=36000 missing^).
  echo         Copy the .env from the V45 package ^(keep your GVM_PASSWORD / tokens^).
  pause & exit /b 2
)
findstr /C:"PORT_PROFILE=full" .env >nul || echo   WARN: PORT_PROFILE is not full - scans will use the fast port list.
echo   ok: package and .env are V45.4
echo.
echo [1] Recreating scanner stack ^(openvas.conf is regenerated by configure-openvas^)...
docker compose stop -t 30 scanner-agent
docker compose rm -f -s scanner-agent configure-openvas >nul 2>&1
docker compose up -d --build --force-recreate configure-openvas openvasd openvas ospd-openvas scanner-agent
if errorlevel 1 (
  echo   FAIL: docker compose up failed. See output above.
  pause & exit /b 1
)
echo.
echo [2] Waiting 25s for the agent banner...
timeout /t 25 /nobreak >nul
echo.
echo [3] openvas.conf inside the scanner ^(expect plugins_timeout = 320, scanner_plugins_timeout = 36000^):
docker compose exec -T openvas cat /etc/openvas/openvas.conf
echo.
echo [4] Agent startup banner ^(expect "AGENT BUILD 1.5.1-v45.4 ... scanner_plugins_timeout=36000s coverage_guard=on"^):
docker compose logs --tail 300 scanner-agent 2>nul | findstr /C:"AGENT BUILD" /C:"DEGRADED SCAN CONFIG" /C:"OpenVAS quality profile"
echo.
echo ------------------------------------------------------------
echo  If [4] shows "DEGRADED SCAN CONFIG" the agent is refusing jobs on purpose:
echo  fix laptop-scanner\.env timeouts and run this script again.
echo  If [4] shows no "AGENT BUILD" line at all, the container is still the old
echo  image/folder: run  docker compose ps  and check the agent's mounted source path.
echo ------------------------------------------------------------
pause
